name: hello-world
on: 
  workflow_dispatch:
    inputs:
      source_directory:
        description: "Enter the source name"
        required: true
        type: string
      destination_directory:
        description: "Enter the destination path"
        required: true
        type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: show-inputs
        run: |
          echo "Hello ${{inputs.source_directory}}"
          echo "Hello ${{inputs.destination_directory}}"
      - name: run-commands
        run: |
          echo "Python Version"
          python --version
          echo "Who AM I"
          whoami
          echo "List directories"
          ls -la
          echo "Present working directories"
          pwd
        
        
        
