name: hello-world
on: 
  workflow_dispatch:
    inputs:
      username:
        description: "Enter the name"
        required: true
        type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: show-username
        run: echo "Hello ${{inputs.username}}"
      - name: run-commands
        run: |
          echo "Python Version"
          python --version
          echo "Who AM I"
          whoami
          echo "List directories"
          ls -la
          echo "Present working directories"
          pwd
        
        
        
