name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: run-commands
        run: python --version
        run: whoami
        run: ls -la
        run: pwd
        
        
        
